name: cd

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

# on:
#   workflow_run:
#       workflows: ["ci"]
#       types:
#         - completed
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u vvovsyannikov --password-stdin

      - name: Pull image to use as a cache
        run: docker pull ghcr.io/vvovsyannikov/tm-web:latest || exit 0

      - name: Build Docker image
        run: docker build . -f Dockerfile.cd --cache-from ghcr.io/vvovsyannikov/tm-web:latest --tag ghcr.io/vvovsyannikov/tm-web:${{ github.sha }}

      - name: Push the image to GitHub Container Registry
        run: docker push ghcr.io/vvovsyannikov/tm-web:${{ github.sha }}

      - name: VPS - pull image and run app containters
        uses: appleboy/ssh-action@master
        with:
          host: 185.246.65.250
          username: deploy
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u vvovsyannikov --password-stdin
            docker stop $(docker ps -a| awk '{print $NF}' | grep -w web)
            docker rm $(docker ps -a | awk '{print $NF}' | grep -w web)
            docker rmi $(docker images | grep 'web')
            docker pull ghcr.io/vvovsyannikov/tm-web:${{ github.sha }}
            cd ~/TaskManager
            tag=${{ github.sha }} docker-compose up -d
